let
Справочник = 
[		readme = "Справочники проекта v 1.0",
        
        //  Справочник форм отчетности
        Спр_ФормыОтчетности = 
            [   Источник = #table(type table 
                    [   Форма_ID        = text, 
                        Название        = text, 
                        КраткоеНазвание = text, 
                        Примечание      = text   ],
                    {   {"0112",    "Баланс",                                               "ББ",   ""}, 
                        {"0212",    "Отчет и прибылях и убытках",                           "ОПУ",  ""},
                        {"0312",    "Отчет о доходах, расходах и финансовых результатах",   "ОДРФР",""},
                        {"0412",    "Отчет о движении денежных средств",                    "ОДДС", ""},
                        {"0512",    "Приложение к бухгалтерскому балансу",                  "ПББ",  ""},
                        {"3012",    "Отчет об изменении капитала",                          "ОИК",  ""},
                        {"0612",    "Отчет о состоянии расчетов",                           "ОСР",  ""},
                        {"06R1",    "Отчет о состоянии расчетов new",                       "ОСР",  ""},
                        {"1212",    "Отчет о финансовых результатах",                       "ОФР",  ""},
                        {"12f1",    "Отчет о финансовых результатах",                       "ОФР",  ""}  }
                )
            ] [Источник],

        // Справочник периодов
        Спр_Год = 
            let Источник = Table.FromList({2017..2022}, Splitter.SplitByNothing()),
                Rename   = Table.RenameColumns(Источник,{{"Column1", "Год"}}),
                Trans    = Table.TransformColumnTypes(Rename,{{"Год", Int64.Type}})
            in  Trans,

        		
	    // Область
	    Спр_Область = 
            let Источник = Table.Buffer(#table(type table [
                        Область_ID 	= number, 
                        Область 	= text	],
                    {
                        {1,"Брест"}, 
                        {2,"Витебск"},
                        {3,"Гомель"},
                        {4,"Гродно"},
                        {5,"Минск"},
                        {6,"Могилев"} 
                    }))
            in Источник,

        
        //------------------------------------------------------------------------------------------
        // Справочники баланса
        БАЛАНС = 
        [
            Спр_ББ_Часть = [
                Источник = #table(type table 
                    [   
                        Часть_ID = number, 
                        ЧастьИмяПолное= text, 
                        ЧастьИмяКраткое = text, 
                        ЧастьАббревиутура = text
                    ],
                    {  
                        {1,	"Активы",								"Актив",	"А"}, 
                        {2,	"Собственный капитал и обязательства", 	"Пассив",	"П"}
                    }
                ) 
            ] [Источник],
            
            // справочник разделов баланса
            Спр_ББ_Раздел = [
                Источник = #table(type table 
                    [
                        Раздел_ID = number, 
                        РазделПрефикс= text, 
                        РазделИмя = text, 
                        РазделИмяПолное = text,
                        РазделИмяСокращенное = text, 
                        РазделИмяАббревиатура = text
                    ],
                    {
                        {1, "Раздел 1", "Долгосрочные активы",         "Раздел 1 Долгосрочные активы",         "ДолгАктивы",  "ДА" }, 
                        {2, "Раздел 2", "Краткосрочные активы",        "Раздел 2 Краткосрочные активы",        "КраткАктивы", "КА" },
                        {3, "Раздел 3", "Собственный капитал",         "Раздел 3 Собственный капитал",         "СобКапитал",  "СК" },
                        {4, "Раздел 4", "Долгосрочные обязательства",  "Раздел 4 Долгосрочные обязательства",  "ДолгОбяз",    "ДО" },
                        {5, "Раздел 5", "Краткосрочные обязательства", "Раздел 5 Краткосрочные обязательства", "КраткОбяз",   "КО" },
                        {0, "Раздел 6", "Забалансовые счета",          "Раздел 0 Забалансовые счета",          "ЗабСчета",    "ЗС" }
                    } ),
                SelectRows0 = Table.SelectRows(Источник, each ([Раздел_ID] <> 0))
            ] [SelectRows0],
        
            // справочник групп статей баланса
            Спр_ББ_Группа = [
                Источник = #table(type table 
                    [
                        Группа_ID = number, 
                        ГруппаИмя = text
                    ],
                    {
                        {1, "Группа"}, 
                        {2, "Подгруппа"}
                    } 
                )
            ] [Источник],

            // справочник уровней баланса
            Спр_ББ_Уровень = 
                let Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUbqw+GLDhX0XNl3YemHvxR4FsNDyCxsuNl5sutijFKsTrWSEqQostODChgvbL2wBCu0GqzPGVAcWWnixCWge0LSL/WB1JpjqwELzgQJbQPYiVMcCAA==", BinaryEncoding.Base64), Compression.Deflate)), 
                    let _t = ((type nullable text) meta [Serialized.Text = true]) 
                    in type table [Уровень_ID = _t, УровеньПрефикс = _t, УровеньИмя = _t]),
                    tr = Table.TransformColumnTypes(Источник,{{"Уровень_ID", Int64.Type}, {"УровеньИмя", type text}})
                in  tr
        ],
    
     // справочник видов деятельности
    ОПУ = 
    [
        Спр_ОПУ_ВидДеятельности = 
            let Источник = #table(type table [   
                    ВидДеятельности_ID  = Int64.Type, 
                    ДиапазонСтрок_ID    = text, 
                    ВидДеятельностиИмя  = text],
                {
                    {1, "10..90",   "Текущая деятельность"}, 
                    {2, "100..140", "Инвестиционная деятельность"},
                    {3, "80..100",  "Другие показатели"}
                }
            )
            in Источник,

        // справочник видов показателей прибыли
        Спр_ОПУ_ВидПрибыли =
            let Источник = #table(type table [ 
                Прибыль_ID = Int64.Type, 
                ПрибыльВид = text ],
            {
                {1, "Показатели прибыли"}, 
                {2, "Другие показатели"}
            } )
        in Источник,

        // справочник групп статей
        Спр_ОПУ_Группа = 
            let Источник = #table(type table [
                Группа_ID = number, 
                ГруппаИмя = text    ],
                {
                    {1,"Группа"}, 
                    {2,"Подгруппа"}
                } )
            in Источник
    ],

    // ОДДС
    ОДДС = 
    [
        Спр_ОДДС_Виды_Деятельности = 
            let Источник = #table(type table [
                    ВидДеятельностиДиапазонСтрок = text, 
                    ВидДеятельности = text  ],
                    {
                        {"20..40","Текущая деятельность"}, 
                        {"50..70","Инвестиционная деятельность"},
                        {"80..100","Финансовая деятельность"}, 
                        {"110..140"," Другое"}
                    }
                ),
                AddIndexColumn  = Table.AddIndexColumn(Источник, "ID_Индекс", 1, 1, Int64.Type),
                ReorderColumns  = Table.ReorderColumns(AddIndexColumn,{"ID_Индекс", "ВидДеятельности", "ВидДеятельностиДиапазонСтрок"}),
                RenameColumns   = Table.RenameColumns(ReorderColumns,{{"ID_Индекс", "ВидДеятельности_ID"}})
            in  RenameColumns,

        // справочник
        Спр_ОДДС_ВидыДвижения = 
            let Источник = #table(type table [
                    ВидДвиженияДиапазонСтрок = text, 
                    ВидДвижения_ID = text],
                    {
                        {"20..24","Поступило"},
                        {"50..55","Поступило"}, 
                        {"80..84","Поступило"}, 
                        {"30..34","Выбыло"},
                        {"60..64","Выбыло"},
                        {"90..95","Выбыло"},
                        {"40","РезультатТек"}, 
                        {"70","РезультатИнв"}, 
                        {"100","РезультатФин"}, 
                        {"110","РезультатОбщий"}, 
                        {"120..140","Другие"}
                    }
                ),
                AddIndexColumn = Table.AddIndexColumn(Источник, "ID_Индекс", 1, 1, Int64.Type),
                ReorderColumns = Table.ReorderColumns(AddIndexColumn,{"ID_Индекс", "ВидДвижения_ID", "ВидДвиженияДиапазонСтрок"})
            in  ReorderColumns
    ] // конец ОДДС

] // конец Справочники
in
    Справочник